symbol: BTCUSDT
streams:
  - btcusdt@trade
  - btcusdt@depth@100ms

ws_base_url: wss://stream.binance.com:9443/stream
rest_base_url: https://api.binance.com

depth_snapshot_limit: 1000

storage:
  raw_dir: data/raw
  trades_dir: data/raw/trades
  depth_updates_dir: data/raw/depth_updates
  depth_snapshots_dir: data/raw/depth_snapshots

flush_every_n_messages: 200
log_every_n_messages: 100